version: '3'
services:
 app:
  build: .
  command: >
    bash -c "bundle exec rails s -b 0.0.0.0 -p 3000"
  ports:
   - 3000:3000
  volumes:
   - ./storage:/app/storage
  environment:
   - DEV_DATABASE_HOST=db
  depends_on:
   - db
  stdin_open: true
  tty: true
 worker:
  shm_size: 2gb
  build:
   context: .
   shm_size: 2gb
  command: >
    bash -c "bundle exec rake db:migrate &&
             bundle exec rake jobs:work"
  volumes:
   - ./storage:/app/storage
  environment:
   - DEV_DATABASE_HOST=db
  depends_on:
   - db
   - app
  stdin_open: true
  tty: true
 db:
  image: mysql:5.7
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=password
   - MYSQL_DATABASE=catalog_development
   - MYSQL_USER=catalog
   - MYSQL_PASSWORD=catalog
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
   - db
  ports:
    - 8080:80
  depends_on:
   - db
  stdin_open: true
  tty: true
volumes:
 storage:
  driver: local
  driver_opts:
   o: bind
   type: none
   device: ./storage
